### ISSUE TITLE
Error after registration

### ISSUE THREAD

**Issue by RichardLovejoy1337** [miraDask/QuizHut#3]
![image](https://user-images.githubusercontent.com/56000018/82127154-27765880-97ba-11ea-945e-9d943a63e78b.png)
![image](https://user-images.githubusercontent.com/56000018/82127166-3ceb8280-97ba-11ea-8d73-617a22c8cd66.png)

**Comment by miraDask** [comment]
This error is because there is no api key, I can't expose SendGrid key at public repository. But I should probably mention it in the readme file of the project.
