### ISSUE TITLE
Error after hitting button "Results", "Events", "Groups"

### ISSUE THREAD

**Issue by RichardLovejoy1337** [miraDask/QuizHut#5]
(Log in as teacher)
![image](https://user-images.githubusercontent.com/56000018/82127369-b041c400-97bb-11ea-8f02-89adbc32e733.png)

![image](https://user-images.githubusercontent.com/56000018/82127418-0151b800-97bc-11ea-90cf-eb63f5fc8acc.png)

**Comment by miraDask** [comment]
This error is because there is no api key, I can't expose SendGrid key at public repository. But I should probably mention it in the readme file of the project.
