### ISSUE TITLE
Error after taking quiz

### ISSUE THREAD

**Issue by RichardLovejoy1337** [miraDask/QuizHut#7]
(Log in as teacher)
![image](https://user-images.githubusercontent.com/56000018/82127485-9654b100-97bc-11ea-9c1a-8e191a3c92d0.png)
![image](https://user-images.githubusercontent.com/56000018/82127480-92289380-97bc-11ea-87b2-a1e1df195dbc.png)

**Comment by miraDask** [comment]
Cache table should be created manualy in the database. Another thing that i will discribe in readme file of the app.
